# Generated by Django 5.2 on 2025-05-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Уникальный идентификатор финансового актива')),
                ('isin', models.CharField(max_length=12, unique=True, verbose_name='Международный идентификационный код ценной бумаги')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('registry_number', models.CharField(blank=True, max_length=50, verbose_name='Регистрационный номер')),
                ('nominal', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Номинал')),
                ('currency', models.CharField(blank=True, max_length=20, verbose_name='Валюта')),
                ('emitent_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН эмитента')),
                ('emitent_name', models.CharField(blank=True, max_length=300, verbose_name='Эмитент')),
                ('list_section', models.CharField(blank=True, max_length=50, verbose_name='Секция листинга')),
                ('registry_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
