# Generated by Django 5.2 on 2025-05-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_main', models.BooleanField(default=False, verbose_name='Является ли основным')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Портфель пользователя',
                'verbose_name_plural': 'Портфели пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/', verbose_name='Аватар')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Электронная почта подтверждена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информации о пользователях',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4, verbose_name='Уникальный идентификатор финансового актива')),
                ('quantity', models.PositiveIntegerField(verbose_name='Число активов')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moex.asset', verbose_name='Финансовый актив')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Актив в портфеле',
                'verbose_name_plural': 'Активы в портфелях',
                'unique_together': {('portfolio', 'ticker')},
            },
        ),
    ]
