# Generated by Django 5.2 on 2025-05-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('moex', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together={('portfolio', 'asset')},
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='ticker',
        ),
    ]
