# Generated by Django 5.2 on 2025-05-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('version', models.CharField(default='1.0.0', max_length=6, verbose_name='Версия')),
                ('path', models.URLField(verbose_name='URL к модели')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Используемая модель нейронной сети',
                'verbose_name_plural': 'Используемые модели нейронных сетей',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('last_prediction_date', models.DateTimeField(verbose_name='Последняя дата и время из предсказаний')),
                ('interval_of_predictions', models.CharField(choices=[('1', '1 мин'), ('10', '10 мин'), ('60', '1 час'), ('24', '1 день')], max_length=2, verbose_name='Интервал предсказаний')),
                ('predicted_values', models.JSONField(verbose_name='Предсказанные значения')),
                ('actual_values', models.JSONField(default=dict, verbose_name='Реальные значения')),
                ('metrics', models.JSONField(default=dict, verbose_name='Метрики')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moex.asset', verbose_name='Финансовый актив')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.mlmodel', verbose_name='Модель нейронной сети')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'Предсказания',
                'unique_together': {('model', 'asset', 'last_prediction_date', 'interval_of_predictions')},
            },
        ),
    ]
